// PIZZAS
export const GET_LIST_PIZZAS_SALGADAS = 'PIZZAS_SALGADAS.::.GET_LIST_PIZZAS_SALGADAS.::.';
export const GET_LIST_PIZZAS_DOCES = 'PIZZAS_DOCES.::.GET_LIST_PIZZAS_DOCES.::.';

// CARRINHO
export const ADD_AO_CARRINHO = 'CARRINHO.::.ADD_AO_CARRINHO.::.';
