// PIZZAS SALGADAS
export const GET_LIST_PIZZAS_SALGADAS_SUCCESS = 'PIZZAS_SALGADAS.::.GET_LIST_PIZZAS_SALGADAS_SUCCESS.::.';
export const LOADING_PIZZAS_SALGADAS = 'PIZZAS_SALGADAS.::.LOADING_PIZZAS_SALGADAS.::.';

// PIZZAS DOCES
export const GET_LIST_PIZZAS_DOCES = 'PIZZAS_DOCES.::.GET_LIST_PIZZAS_DOCES.::.';

// CARRINHO
export const ADD_AO_CARRINHO = 'CARRINHO.::.ADD_AO_CARRINHO.::.';
export const SET_FORMA_PG = 'CARRINHO.::.SET_FORMA_PG.::.';
export const SAVE_PEDIDO = 'CARRINHO.::.SAVE_PEDIDO.::.';
